from django.urls import re_path
from .controllers import (
    LoginController,
    AccountListController,
    AccountDeleteController,
    ExitRecordController,
    EntryRecordController,
    ReturnRecordController,
    RealtimeStatisticsController,
    WorkStatisticsController,
    RecordListController,
    RecordExportController,
    ExitTypeListController,
    ExitTypeAddController,
    ExitTypeUpdateController,
    ExitTypeDeleteController,
    PrisonMessagesController,
)

urlpatterns = [
    re_path(r'^user_login/user_login_web/?$', LoginController.as_view(), name='login'),
    re_path(r'^account/account_list/?$', AccountListController.as_view(), name='account_list'),
    re_path(r'^account/account_add/?$', AccountListController.as_view(), name='account_add'),
    re_path(r'^account/account_delete/?$', AccountDeleteController.as_view(), name='account_delete'),
    re_path(r'^exit_record/submit/?$', ExitRecordController.as_view(), name='exit_record'),
    re_path(r'^entry_record/submit/?$', EntryRecordController.as_view(), name='entry_record'),
    re_path(r'^return_record/submit/?$', ReturnRecordController.as_view(), name='return_record'),
    re_path(r'^statistics/realtime/?$', RealtimeStatisticsController.as_view(), name='realtime_statistics'),
    re_path(r'^statistics/work/?$', WorkStatisticsController.as_view(), name='work_statistics'),
    re_path(r'^record/list/?$', RecordListController.as_view(), name='record_list'),
    re_path(r'^record/export/?$', RecordExportController.as_view(), name='record_export'),
    re_path(r'^record/prison_messages/?$', PrisonMessagesController.as_view(), name='prison_messages'),
    re_path(r'^exit_type/list/?$', ExitTypeListController.as_view(), name='exit_type_list'),
    re_path(r'^exit_type/add/?$', ExitTypeAddController.as_view(), name='exit_type_add'),
    re_path(r'^exit_type/update/?$', ExitTypeUpdateController.as_view(), name='exit_type_update'),
    re_path(r'^exit_type/delete/?$', ExitTypeDeleteController.as_view(), name='exit_type_delete'),
]
