# 摄像头配置
cameras:
  - channel: "1601"
    name: "摄像头1"
    enabled: true
    rtsp_url: "rtsp://admin:root123a@192.168.100.150:554/Streaming/tracks/1601"
    # 是否启用认证
    auth_enabled: true

  - channel: "1602"
    name: "摄像头2"
    enabled: false
    rtsp_url: ""
    # 是否启用认证
    auth_enabled: true