# Generated by Django 4.2.30 on 2026-05-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitEntryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prisoner_no', models.CharField(max_length=32, verbose_name='罪犯编号')),
                ('prisoner_name', models.CharField(max_length=64, verbose_name='罪犯姓名')),
                ('prisoner_photo', models.CharField(blank=True, max_length=255, verbose_name='罪犯照片')),
                ('prison_area', models.CharField(blank=True, max_length=32, verbose_name='分监区ID')),
                ('prison_area_name', models.CharField(blank=True, max_length=128, verbose_name='分监区名称')),
                ('type', models.CharField(choices=[('exit', '出监'), ('entry', '入监')], max_length=16, verbose_name='类型')),
                ('reason', models.CharField(blank=True, max_length=32, verbose_name='出监原因')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='出监日期')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='入监日期')),
                ('police_face', models.CharField(blank=True, max_length=255, verbose_name='民警人脸')),
                ('police_name', models.CharField(blank=True, max_length=64, verbose_name='民警姓名')),
                ('swat_face', models.CharField(blank=True, max_length=255, verbose_name='特警人脸')),
                ('swat_name', models.CharField(blank=True, max_length=64, verbose_name='特警姓名')),
                ('armed_police_signature', models.TextField(blank=True, verbose_name='武警签名')),
                ('armed_police_name', models.CharField(blank=True, max_length=64, verbose_name='武警姓名')),
                ('operator_id', models.IntegerField(null=True, verbose_name='操作人ID')),
                ('operator_name', models.CharField(blank=True, max_length=64, verbose_name='操作人')),
                ('status', models.CharField(default='processing', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'exit_entry_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prison_area', models.CharField(max_length=32, verbose_name='分监区ID')),
                ('prison_area_name', models.CharField(max_length=128, verbose_name='分监区名称')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('exit_count', models.IntegerField(default=0, verbose_name='出监总人数')),
                ('exit_reason_1', models.IntegerField(default=0, verbose_name='刑满释放')),
                ('exit_reason_2', models.IntegerField(default=0, verbose_name='外出就医')),
                ('exit_reason_3', models.IntegerField(default=0, verbose_name='外出教育')),
                ('exit_reason_4', models.IntegerField(default=0, verbose_name='离监探亲')),
                ('exit_reason_5', models.IntegerField(default=0, verbose_name='押回重审')),
                ('entry_count', models.IntegerField(default=0, verbose_name='入监总人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'history_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('user', '普通用户')], default='user', max_length=32, verbose_name='角色'),
        ),
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prison_area', models.CharField(max_length=32, verbose_name='分监区ID')),
                ('prison_area_name', models.CharField(max_length=128, verbose_name='分监区名称')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('exit_count', models.IntegerField(default=0, verbose_name='出监总人数')),
                ('exit_reason_1', models.IntegerField(default=0, verbose_name='刑满释放')),
                ('exit_reason_2', models.IntegerField(default=0, verbose_name='外出就医')),
                ('exit_reason_3', models.IntegerField(default=0, verbose_name='外出教育')),
                ('exit_reason_4', models.IntegerField(default=0, verbose_name='离监探亲')),
                ('exit_reason_5', models.IntegerField(default=0, verbose_name='押回重审')),
                ('entry_count', models.IntegerField(default=0, verbose_name='入监总人数')),
                ('in_prison_count', models.IntegerField(default=0, verbose_name='实时在监人数')),
                ('work_count', models.IntegerField(default=0, verbose_name='出工人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'daily_statistics',
                'unique_together': {('prison_area', 'date')},
            },
        ),
    ]
