# Generated by Django 4.2.30 on 2026-05-17 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_exitentryrecord_historystatistics_alter_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=128, verbose_name='出监原因')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='层级')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('active', '启用'), ('disabled', '停用')], default='active', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.exittype', verbose_name='上级出监原因')),
            ],
            options={
                'db_table': 'exit_type',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['parent', 'sort_order', 'id'], name='exit_type_parent__b36308_idx'), models.Index(fields=['type_name'], name='exit_type_type_na_aa5204_idx')],
            },
        ),
    ]
