# Generated by Django 4.2.30 on 2026-05-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_exittype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystatistics',
            name='exit_reason_1',
        ),
        migrations.RemoveField(
            model_name='dailystatistics',
            name='exit_reason_2',
        ),
        migrations.RemoveField(
            model_name='dailystatistics',
            name='exit_reason_3',
        ),
        migrations.RemoveField(
            model_name='dailystatistics',
            name='exit_reason_4',
        ),
        migrations.RemoveField(
            model_name='dailystatistics',
            name='exit_reason_5',
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='reason_stats',
            field=models.JSONField(default=dict, verbose_name='出监原因统计'),
        ),
    ]
