# Generated by Django 4.2.30 on 2026-05-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_dailystatistics_exit_reason_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitentryrecord',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='医院名称'),
        ),
        migrations.AddField(
            model_name='exitentryrecord',
            name='hospital_type',
            field=models.CharField(blank=True, max_length=32, verbose_name='医院类型'),
        ),
    ]
