# Generated by Django 4.2.30 on 2026-05-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_hospital_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitentryrecord',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='医院名称'),
        ),
        migrations.AlterField(
            model_name='exitentryrecord',
            name='hospital_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='医院类型'),
        ),
    ]
