# Generated by Django 4.2.30 on 2026-05-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_allow_hospital_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitentryrecord',
            name='attachments',
            field=models.JSONField(blank=True, default=list, verbose_name='附件'),
        ),
    ]
