# Generated by Django 4.2.30 on 2026-05-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_attachments_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitentryrecord',
            name='abnormal_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='异常原因'),
        ),
        migrations.AlterField(
            model_name='dailystatistics',
            name='prison_area',
            field=models.CharField(max_length=32, verbose_name='监区ID'),
        ),
        migrations.AlterField(
            model_name='dailystatistics',
            name='prison_area_name',
            field=models.CharField(max_length=128, verbose_name='监区名称'),
        ),
        migrations.AlterField(
            model_name='exitentryrecord',
            name='prison_area',
            field=models.CharField(blank=True, max_length=32, verbose_name='监区ID'),
        ),
        migrations.AlterField(
            model_name='exitentryrecord',
            name='prison_area_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='监区名称'),
        ),
        migrations.AlterField(
            model_name='historystatistics',
            name='prison_area',
            field=models.CharField(max_length=32, verbose_name='监区ID'),
        ),
        migrations.AlterField(
            model_name='historystatistics',
            name='prison_area_name',
            field=models.CharField(max_length=128, verbose_name='监区名称'),
        ),
    ]
