# Generated by Django 4.2.30 on 2026-06-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_time_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrisonerArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prisoner_no', models.CharField(max_length=32, unique=True, verbose_name='罪犯编号')),
                ('prisoner_name', models.CharField(blank=True, default='', max_length=64, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, default='', max_length=8, verbose_name='性别')),
                ('birth_date', models.CharField(blank=True, default='', max_length=20, verbose_name='出生日期')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('id_card', models.CharField(blank=True, default='', max_length=32, verbose_name='身份证号')),
                ('nation', models.CharField(blank=True, default='', max_length=32, verbose_name='民族')),
                ('education', models.CharField(blank=True, default='', max_length=32, verbose_name='文化程度')),
                ('marital_status', models.CharField(blank=True, default='', max_length=16, verbose_name='婚姻状况')),
                ('native_place', models.CharField(blank=True, default='', max_length=128, verbose_name='籍贯')),
                ('address', models.CharField(blank=True, default='', max_length=256, verbose_name='家庭地址')),
                ('crime', models.CharField(blank=True, default='', max_length=128, verbose_name='罪名')),
                ('sentence', models.CharField(blank=True, default='', max_length=64, verbose_name='原判刑期')),
                ('sentence_start', models.CharField(blank=True, default='', max_length=20, verbose_name='刑期起日')),
                ('sentence_end', models.CharField(blank=True, default='', max_length=20, verbose_name='刑期止日')),
                ('prison_area', models.CharField(blank=True, default='', max_length=64, verbose_name='监区')),
                ('room_no', models.CharField(blank=True, default='', max_length=32, verbose_name='监室号')),
                ('bed_no', models.CharField(blank=True, default='', max_length=32, verbose_name='床号')),
                ('status', models.CharField(blank=True, default='', max_length=32, verbose_name='在押状态')),
                ('entry_date', models.CharField(blank=True, default='', max_length=20, verbose_name='入监日期')),
                ('arrest_org', models.CharField(blank=True, default='', max_length=128, verbose_name='逮捕机关')),
                ('judgment_org', models.CharField(blank=True, default='', max_length=128, verbose_name='判决机关')),
                ('judgment_no', models.CharField(blank=True, default='', max_length=128, verbose_name='判决书号')),
                ('basic_info', models.JSONField(blank=True, default=dict, verbose_name='基础信息完整数据')),
                ('media_info', models.JSONField(blank=True, default=list, help_text='每条包含: media_code, media_category, photo_path, remark', verbose_name='媒体信息列表')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '罪犯档案',
                'verbose_name_plural': '罪犯档案',
                'db_table': 'prisoner_archive',
                'ordering': ['prisoner_no'],
            },
        ),
    ]
