# Generated by Django 4.2.30 on 2026-07-07 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_exit_entry_datetime'),
    ]

    operations = [
        # armed_police_face 字段已通过 SQL 手动添加，跳过迁移
    ]
