# Generated by Django 4.2.30 on 2026-07-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_last_synced_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayExitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prisoner_no', models.CharField(max_length=32, unique=True, verbose_name='罪犯编号')),
                ('prisoner_name', models.CharField(max_length=64, verbose_name='罪犯姓名')),
                ('prison_area', models.CharField(max_length=32, verbose_name='监区ID')),
                ('prison_area_name', models.CharField(max_length=128, verbose_name='监区名称')),
                ('exit_reason', models.CharField(max_length=64, verbose_name='出监原因')),
                ('exit_date', models.DateTimeField(verbose_name='出监时间')),
            ],
            options={
                'db_table': 'today_exit_records',
            },
        ),
        migrations.AddField(
            model_name='exitentryrecord',
            name='armed_police_face',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='武警人脸照片'),
        ),
        migrations.AddField(
            model_name='exitentryrecord',
            name='video_url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='录像存储URL'),
        ),
        migrations.AlterField(
            model_name='exitentryrecord',
            name='prisoner_photo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='罪犯照片'),
        ),
    ]
