# Generated by Django 4.2.30 on 2026-09-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_add_device_and_handheld_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandheldSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prisoner_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='罪犯编号')),
                ('person_synced', models.BooleanField(default=False, verbose_name='人员已注册')),
                ('photo_synced', models.BooleanField(default=False, verbose_name='照片已注册')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='最近同步时间')),
            ],
            options={
                'verbose_name': '手持终端同步记录',
                'verbose_name_plural': '手持终端同步记录',
                'db_table': 'handheld_sync_log',
            },
        ),
    ]
